CREATE TABLE [dbo].[MI_REPORTING_TABLEAU_FeeDebt] (
    [MI_ID]                                INT             IDENTITY (1, 1) NOT NULL,
    [Business Unit]                        NVARCHAR (300)  NULL,
    [BU Descr]                             NVARCHAR (300)  NULL,
    [Account]                              NVARCHAR (300)  NULL,
    [Alt Acct]                             NVARCHAR (300)  NULL,
    [GL Client ID]                         NVARCHAR (100)  NULL,
    [GL Client Descr]                      NVARCHAR (300)  NULL,
    [Func Unit ID]                         NVARCHAR (100)  NULL,
    [Func Unit Descr]                      NVARCHAR (300)  NULL,
    [FU TNL 6 Descr]                       NVARCHAR (300)  NULL,
    [Mang Office ID]                       NVARCHAR (100)  NULL,
    [Mang Office Descr]                    NVARCHAR (300)  NULL,
    [Mang Office TNL 8 Descr]              NVARCHAR (300)  NULL,
    [FUMO ID]                              NVARCHAR (100)  NULL,
    [Geos Super Region]                    NVARCHAR (300)  NULL,
    [Proj Mgr ID]                          NVARCHAR (100)  NULL,
    [Proj Mgr Name]                        NVARCHAR (300)  NULL,
    [Cust Cont]                            NVARCHAR (300)  NULL,
    [Project]                              NVARCHAR (300)  NULL,
    [Proj Descr]                           NVARCHAR (300)  NULL,
    [Property Reference]                   NVARCHAR (100)  NULL,
    [Self Pay/Client Pay]                  NVARCHAR (100)  NULL,
    [Project Type]                         NVARCHAR (100)  NULL,
    [Proj Type Descr]                      NVARCHAR (300)  NULL,
    [Bill Cust ID]                         NVARCHAR (300)  NULL,
    [Bill Cust Name]                       NVARCHAR (300)  NULL,
    [Bill Cust Addr]                       NVARCHAR (4000) NULL,
    [Sold To Cust ID]                      NVARCHAR (100)  NULL,
    [Sold Cust Name]                       NVARCHAR (300)  NULL,
    [Bill Cust Type Descr]                 NVARCHAR (300)  NULL,
    [Property]                             NVARCHAR (300)  NULL,
    [Prop Descr]                           NVARCHAR (300)  NULL,
    [Cust Supp Team]                       NVARCHAR (100)  NULL,
    [Item ID]                              NVARCHAR (300)  NULL,
    [Bill Hdr Note]                        NVARCHAR (300)  NULL,
    [PO Ref]                               NVARCHAR (300)  NULL,
    [Reason]                               NVARCHAR (100)  NULL,
    [Original Invoice ID]                  NVARCHAR (300)  NULL,
    [Orig Invoice Dt]                      DATE            NULL,
    [Invoice Dt]                           DATE            NULL,
    [Due Date]                             DATE            NULL,
    [Acctg Date]                           DATE            NULL,
    [Inv Amt-Base]                         DECIMAL (18, 2) NULL,
    [VAT-Base]                             DECIMAL (18, 2) NULL,
    [Net Amt-Base]                         DECIMAL (18, 2) NULL,
    [Invoice Amount]                       DECIMAL (18, 2) NULL,
    [Total VAT Amnt]                       DECIMAL (18, 2) NULL,
    [Net Amount]                           DECIMAL (18, 2) NULL,
    [Inv Currency]                         NVARCHAR (100)  NULL,
    [Open Amt]                             DECIMAL (18, 2) NULL,
    [Days Old]                             INT             NULL,
    [Aging Buc/Cat]                        NVARCHAR (100)  NULL,
    [Conversation]                         NVARCHAR (4000) NULL,
    [Parent Cust ID]                       NVARCHAR (100)  NULL,
    [P&L Name]                             VARCHAR (100)   NULL,
    [FUMO]                                 VARCHAR (100)   NULL,
    [P&L Owner]                            VARCHAR (100)   NULL,
    [PM / FM]                              VARCHAR (100)   NULL,
    [accounting_db]                        NVARCHAR (300)  NULL,
    [client_ref]                           NVARCHAR (300)  NULL,
    [property_ref]                         NVARCHAR (300)  NULL,
    [PCD Client Name]                      NVARCHAR (600)  NULL,
    [PCD Client Parent Name]               NVARCHAR (600)  NULL,
    [as_project_code]                      VARCHAR (100)   NULL,
    [contact_type]                         NVARCHAR (300)  NULL,
    [contact_nt_username]                  NVARCHAR (600)  NULL,
    [CSD Source]                           NVARCHAR (4000) NULL,
    [emailaddress]                         NVARCHAR (4000) NULL,
    [phone]                                NVARCHAR (4000) NULL,
    [Client Accounting Management Contact] NVARCHAR (4000) NULL,
    [Surveyor]                             NVARCHAR (4000) NULL,
    [SharePoint File URL]                  NVARCHAR (4000) NULL,
    [UNC Path]                             NVARCHAR (4000) NULL,
    [InvoiceSupplierCode]                  NVARCHAR (100)  NULL,
    [SupplierInvoiceNo]                    NVARCHAR (300)  NULL,
    [InvoiceDisplayNo]                     NVARCHAR (100)  NULL,
    [SupplierInvoiceDate]                  DATE            NULL,
    [TotalNetValue]                        DECIMAL (18, 2) NULL,
    [TotalGrossValue]                      DECIMAL (18, 2) NULL,
    [InvoiceStatusDescription]             NVARCHAR (300)  NULL,
    [PaymentStatus]                        NVARCHAR (100)  NULL,
    [PaymentDate]                          DATE            NULL,
    [PaymentComment]                       NVARCHAR (4000) NULL,
    [supplier_invoice_no]                  NVARCHAR (600)  NULL,
    [invoice_status]                       NVARCHAR (600)  NULL,
    [invoice_tray]                         NVARCHAR (600)  NULL,
    [Fee Debt Invoice Status]              NVARCHAR (100)  NULL,
    [Data Date Time]                       DATETIME        NULL,
    [Data Date]                            DATE            NULL,
    CONSTRAINT [MI_ID38_pk] PRIMARY KEY CLUSTERED ([MI_ID] ASC)
);

