CREATE TABLE [dbo].[MI_REPORTING_STAGING_Arrears_MandG_RL] (
    [MI_ID]                                  INT            IDENTITY (1, 1) NOT NULL,
    [Fund]                                   NVARCHAR (255) NULL,
    [Property No#]                           FLOAT (53)     NULL,
    [Property Status]                        NVARCHAR (255) NULL,
    [Unit_Let No#]                           FLOAT (53)     NULL,
    [Unit Name]                              NVARCHAR (255) NULL,
    [Property Name]                          NVARCHAR (255) NULL,
    [Property Address/City/Town]             NVARCHAR (255) NULL,
    [Lease No#]                              NVARCHAR (255) NULL,
    [Tenant]                                 NVARCHAR (255) NULL,
    [Customer No#]                           NVARCHAR (255) NULL,
    [Invoiced Amount]                        FLOAT (53)     NULL,
    [Outstanding_Amount]                     FLOAT (53)     NULL,
    [Charge Description]                     NVARCHAR (255) NULL,
    [Recoverability]                         NVARCHAR (255) NULL,
    [Doc _Seq No#]                           FLOAT (53)     NULL,
    [From Date]                              DATETIME       NULL,
    [To Date]                                DATETIME       NULL,
    [Due Date]                               DATETIME       NULL,
    [Effective Date]                         DATETIME       NULL,
    [Control No#_ETL]                        FLOAT (53)     NULL,
    [Aged Debt]                              NVARCHAR (255) NULL,
    [Days Overdue from Due Date]             FLOAT (53)     NULL,
    [Days Overdue from Effective Date]       FLOAT (53)     NULL,
    [Comments]                               NVARCHAR (MAX) NULL,
    [Contact No#]                            NVARCHAR (255) NULL,
    [Contact Email (billing) (Mailto)]       NVARCHAR (255) NULL,
    [Email-Alt Contact (Mailto)]             NVARCHAR (255) NULL,
    [Contact Notes]                          NVARCHAR (255) NULL,
    [Lease Stat]                             NVARCHAR (255) NULL,
    [End Date ]                              DATETIME       NULL,
    [Covenant Rating]                        NVARCHAR (255) NULL,
    [Property Manager]                       NVARCHAR (255) NULL,
    [Asset Manager]                          NVARCHAR (255) NULL,
    [Fund Manager]                           NVARCHAR (255) NULL,
    [Credit Controller]                      NVARCHAR (255) NULL,
    [Billing Address 1]                      NVARCHAR (255) NULL,
    [Billing Address 2]                      NVARCHAR (255) NULL,
    [Billing Address 3]                      NVARCHAR (255) NULL,
    [Billing Address 4]                      NVARCHAR (255) NULL,
    [Billing Address Post Code]              NVARCHAR (255) NULL,
    [Contact Name (Billing contact)]         NVARCHAR (255) NULL,
    [Stop Type]                              NVARCHAR (255) NULL,
    [Contact Email (billing)]                NVARCHAR (255) NULL,
    [Email-Alt Contact]                      NVARCHAR (255) NULL,
    [Original Tenant?]                       NVARCHAR (255) NULL,
    [Assigned Date]                          NVARCHAR (255) NULL,
    [Previous Assignor Name]                 NVARCHAR (255) NULL,
    [Guarantor(s)]                           NVARCHAR (255) NULL,
    [Original Priority]                      NVARCHAR (255) NULL,
    [Phasing# CC]                            NVARCHAR (255) NULL,
    [Lease Concession]                       NVARCHAR (255) NULL,
    [Concession Start Date]                  DATETIME       NULL,
    [Concession End Date]                    DATETIME       NULL,
    [Batch ID]                               FLOAT (53)     NULL,
    [Control No]                             NVARCHAR (255) NULL,
    [Fund Name]                              NVARCHAR (255) NULL,
    [Sector]                                 NVARCHAR (255) NULL,
    [Control_Account]                        FLOAT (53)     NULL,
    [Charge Code ID]                         NVARCHAR (255) NULL,
    [VAT Code]                               NVARCHAR (255) NULL,
    [Ind/Com]                                NVARCHAR (255) NULL,
    [Parent Debtor]                          FLOAT (53)     NULL,
    [Company Reg #]                          NVARCHAR (50)  NULL,
    [VAT Deadline]                           NVARCHAR (255) NULL,
    [Ageing]                                 NVARCHAR (255) NULL,
    [True Overdue from Effective]            FLOAT (53)     NULL,
    [Over 21+ terms Adj]                     FLOAT (53)     NULL,
    [Over 21+ terms Adj + Effective Dat Adj] FLOAT (53)     NULL,
    [Fund Group]                             NVARCHAR (255) NULL,
    [Quarter Flag]                           NVARCHAR (255) NULL,
    [RET or COM + RT + Q From + Q To]        FLOAT (53)     NULL,
    [Q unmatched amount]                     FLOAT (53)     NULL,
    [Q Adj]                                  FLOAT (53)     NULL,
    [True Unmatched Balance]                 FLOAT (53)     NULL,
    [Adjusted Balance]                       FLOAT (53)     NULL,
    [a) Future]                              FLOAT (53)     NULL,
    [b) <30 Days]                            FLOAT (53)     NULL,
    [c) >30 Days]                            FLOAT (53)     NULL,
    [d) >60 Days]                            FLOAT (53)     NULL,
    [e) >90 Days]                            FLOAT (53)     NULL,
    [f) >120 Days]                           FLOAT (53)     NULL,
    [g) >365 Days]                           FLOAT (53)     NULL,
    [h) Grand Total]                         FLOAT (53)     NULL,
    [Filename]                               NVARCHAR (255) NULL,
    [Data Date Time]                         DATETIME       NULL,
    [Data Date]                              DATE           NULL,
    CONSTRAINT [MI_ID50_pk] PRIMARY KEY CLUSTERED ([MI_ID] ASC)
);


GO
GRANT ALTER
    ON OBJECT::[dbo].[MI_REPORTING_STAGING_Arrears_MandG_RL] TO [db_truncator]
    AS [dbo];

