CREATE TABLE [dbo].[MI_REPORTING_STAGING_CompaniesHouseBasicData] (
    [CompanyName]                        VARCHAR (600)  NULL,
    [CompanyNumber]                      VARCHAR (50)   NOT NULL,
    [RegAddress CareOf]                  VARCHAR (300)  NULL,
    [RegAddress POBox]                   VARCHAR (50)   NULL,
    [RegAddress AddressLine1]            VARCHAR (600)  NULL,
    [RegAddress AddressLine2]            VARCHAR (50)   NULL,
    [RegAddress PostTown]                VARCHAR (50)   NULL,
    [RegAddress County]                  VARCHAR (50)   NULL,
    [RegAddress Country]                 VARCHAR (50)   NULL,
    [RegAddress PostCode]                VARCHAR (50)   NULL,
    [CompanyCategory]                    VARCHAR (300)  NULL,
    [CompanyStatus]                      VARCHAR (50)   NULL,
    [CountryOfOrigin]                    VARCHAR (50)   NULL,
    [DissolutionDate]                    VARCHAR (50)   NULL,
    [IncorporationDate]                  VARCHAR (50)   NULL,
    [Accounts AccountRefDay]             VARCHAR (50)   NULL,
    [Accounts AccountRefMonth]           VARCHAR (50)   NULL,
    [Accounts NextDueDate]               VARCHAR (50)   NULL,
    [Accounts LastMadeUpDate]            VARCHAR (50)   NULL,
    [Accounts AccountCategory]           VARCHAR (50)   NULL,
    [Returns NextDueDate]                VARCHAR (50)   NULL,
    [Returns LastMadeUpDate]             VARCHAR (50)   NULL,
    [Mortgages NumMortCharges]           VARCHAR (50)   NULL,
    [Mortgages NumMortOutstanding]       VARCHAR (50)   NULL,
    [Mortgages NumMortPartSatisfied]     VARCHAR (50)   NULL,
    [Mortgages NumMortSatisfied]         VARCHAR (50)   NULL,
    [SICCode SicText_1]                  VARCHAR (300)  NULL,
    [SICCode SicText_2]                  VARCHAR (300)  NULL,
    [SICCode SicText_3]                  VARCHAR (300)  NULL,
    [SICCode SicText_4]                  VARCHAR (300)  NULL,
    [LimitedPartnerships NumGenPartners] VARCHAR (50)   NULL,
    [LimitedPartnerships NumLimPartners] VARCHAR (50)   NULL,
    [URI]                                VARCHAR (50)   NULL,
    [PreviousName_1 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_1 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_2 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_2 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_3 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_3 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_4 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_4 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_5 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_5 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_6 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_6 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_7 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_7 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_8 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_8 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_9 CONDATE]             VARCHAR (50)   NULL,
    [PreviousName_9 CompanyName]         VARCHAR (600)  NULL,
    [PreviousName_10 CONDATE]            VARCHAR (50)   NULL,
    [PreviousName_10 CompanyName]        VARCHAR (600)  NULL,
    [ConfStmtNextDueDate]                VARCHAR (50)   NULL,
    [ConfStmtLastMadeUpDate]             VARCHAR (50)   NULL,
    [Data Date]                          DATETIME       NULL,
    [Data Date Time]                     DATETIME       NULL,
    [Filename]                           NVARCHAR (300) NULL,
    CONSTRAINT [MI_CompanyNumber] PRIMARY KEY CLUSTERED ([CompanyNumber] ASC)
);


GO
GRANT ALTER
    ON OBJECT::[dbo].[MI_REPORTING_STAGING_CompaniesHouseBasicData] TO [db_truncator]
    AS [dbo];

