CREATE TABLE [dbo].[NationalStatistics_PostcodeLookup] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [pcd]            VARCHAR (50)   NULL,
    [pcd2]           VARCHAR (50)   NULL,
    [pcds]           VARCHAR (50)   NULL,
    [dointr]         VARCHAR (50)   NULL,
    [doterm]         VARCHAR (50)   NULL,
    [usertype]       VARCHAR (50)   NULL,
    [oseast1m]       VARCHAR (50)   NULL,
    [osnrth1m]       VARCHAR (50)   NULL,
    [osgrdind]       VARCHAR (50)   NULL,
    [oa11]           VARCHAR (50)   NULL,
    [cty]            VARCHAR (50)   NULL,
    [ced]            VARCHAR (50)   NULL,
    [laua]           VARCHAR (50)   NULL,
    [ward]           VARCHAR (50)   NULL,
    [hlthau]         VARCHAR (50)   NULL,
    [nhser]          VARCHAR (50)   NULL,
    [ctry]           VARCHAR (50)   NULL,
    [rgn]            VARCHAR (50)   NULL,
    [pcon]           VARCHAR (50)   NULL,
    [eer]            VARCHAR (50)   NULL,
    [teclec]         VARCHAR (50)   NULL,
    [ttwa]           VARCHAR (50)   NULL,
    [pct]            VARCHAR (50)   NULL,
    [itl]            VARCHAR (50)   NULL,
    [park]           VARCHAR (50)   NULL,
    [lsoa11]         VARCHAR (50)   NULL,
    [msoa11]         VARCHAR (50)   NULL,
    [wz11]           VARCHAR (50)   NULL,
    [ccg]            VARCHAR (50)   NULL,
    [bua11]          VARCHAR (50)   NULL,
    [buasd11]        VARCHAR (50)   NULL,
    [ru11ind]        VARCHAR (50)   NULL,
    [oac11]          VARCHAR (50)   NULL,
    [lat]            VARCHAR (50)   NULL,
    [long]           VARCHAR (50)   NULL,
    [lep1]           VARCHAR (50)   NULL,
    [lep2]           VARCHAR (50)   NULL,
    [pfa]            VARCHAR (50)   NULL,
    [imd]            VARCHAR (50)   NULL,
    [calncv]         VARCHAR (50)   NULL,
    [stp]            VARCHAR (50)   NULL,
    [Filename]       NVARCHAR (600) NULL,
    [Data Date]      DATE           NULL,
    [Data Date Time] DATETIME       NULL
);

